wflow-core/src/main/java/org/joget/apps/form/lib/CheckBox.java
package org.joget.apps.form.lib;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import org.joget.apps.app.service.AppUtil;
import org.joget.apps.form.model.FormBuilderPaletteElement;
import org.joget.apps.form.model.FormBuilderPalette;
import org.joget.apps.form.model.FormData;
import org.joget.apps.form.model.FormRow;
import org.joget.apps.form.model.FormRowSet;
import org.joget.apps.form.service.FormUtil;
import org.joget.commons.util.ResourceBundleUtil;

public class CheckBox extends SelectBox implements FormBuilderPaletteElement {

    @Override
    public String getName() {
        return "Check Box";
    }

    @Override
    public String getVersion() {
        return "5.0.0";
    }

    @Override
    public String getDescription() {
        return "Check Box Element";
    }

    @Override
    public FormRowSet formatData(FormData formData) {
        FormRowSet rowSet = null;

        // get value
        String id = getPropertyString(FormUtil.PROPERTY_ID);
        if (id != null) {
            String[] values = FormUtil.getElementPropertyValues(this, formData);
            if (values != null && values.length > 0) {
                // check for empty submission via parameter
                String[] paramValues = FormUtil.getRequestParameterValues(this, formData);
                if ((paramValues == null || paramValues.length == 0) && FormUtil.isFormSubmitted(this, formData)) {
                    values = new String[]{""};
                }

                // formulate values
                String delimitedValue = FormUtil.generateElementPropertyValues(values);

                // set value into Properties and FormRowSet object
                FormRow result = new FormRow();
                result.setProperty(id, delimitedValue);
                rowSet = new FormRowSet();
                rowSet.add(result);
            }
        }

        return rowSet;
    }

    @Override
    public String renderTemplate(FormData formData, Map dataModel) {
        String template = "checkBox.ftl";
        
        dynamicOptions(formData);
        
        // set value
        String[] valueArray = FormUtil.getElementPropertyValues(this, formData);
        List<String> values = Arrays.asList(valueArray);
        dataModel.put("values", values);

        // set options
        Collection<Map> optionMap = getOptionMap(formData);
        dataModel.put("options", optionMap);

        String html = FormUtil.generateElementHtml(this, formData, template, dataModel);
        return html;
    }

    @Override
    public String getClassName() {
        return getClass().getName();
    }

    @Override
    public String getFormBuilderTemplate() {
        return "<label class='label'>" + ResourceBundleUtil.getMessage("org.joget.apps.form.lib.CheckBox.pluginLabel") + "</label><label><input type='checkbox' value='Option' style='color:silver' />" + ResourceBundleUtil.getMessage("form.checkbox.template.options") + "</label>";
    }

    @Override
    public String getLabel() {
        return "Check Box";
    }

    @Override
    public String getPropertyOptions() {
        return AppUtil.readPluginResource(getClass().getName(), "/properties/form/checkbox.json", null, true, "message/form/CheckBox");
    }

    @Override
    public String getFormBuilderCategory() {
        return FormBuilderPalette.CATEGORY_GENERAL;
    }

    @Override
    public int getFormBuilderPosition() {
        return 400;
    }

    @Override
    public String getFormBuilderIcon() {
        return "<i class=\"far fa-check-square\"></i>";
    }
}

wflow-core/src/main/java/org/joget/apps/form/lib/HiddenField.java
package org.joget.apps.form.lib;

import java.util.Map;
import org.joget.apps.app.service.AppUtil;
import org.joget.apps.form.model.Element;
import org.joget.apps.form.model.FormBuilderPaletteElement;
import org.joget.apps.form.model.FormBuilderPalette;
import org.joget.apps.form.model.FormData;
import org.joget.apps.form.model.FormRow;
import org.joget.apps.form.model.FormRowSet;
import org.joget.apps.form.service.FormUtil;
import org.joget.commons.util.ResourceBundleUtil;

public class HiddenField extends Element implements FormBuilderPaletteElement {

    @Override
    public String getName() {
        return "Hidden Field";
    }

    @Override
    public String getVersion() {
        return "5.0.0";
    }

    @Override
    public String getDescription() {
        return "Hidden Field Element";
    }

    @Override
    public String renderTemplate(FormData formData, Map dataModel) {
        String template = "hiddenField.ftl";

        // set value
        String value = FormUtil.getElementPropertyValue(this, formData);
        String priority = getPropertyString("useDefaultWhenEmpty");
        
        if (priority != null && !priority.isEmpty()) {
            if (("true".equals(priority) && (value == null || value.isEmpty()))
                    || "valueOnly".equals(priority)) {
                value = getPropertyString("value");
            }
        } else {
            if (getPropertyString("value") != null && !getPropertyString("value").isEmpty()) {
                value = getPropertyString("value");
            }
        } 

        dataModel.put("value", value);

        String html = FormUtil.generateElementHtml(this, formData, template, dataModel);
        return html;
    }

    @Override
    public String getClassName() {
        return getClass().getName();
    }

    @Override
    public String getFormBuilderTemplate() {
        return "<label class='label'>" + ResourceBundleUtil.getMessage("org.joget.apps.form.lib.HiddenField.pluginLabel") + "</label>";
    }

    @Override
    public String getLabel() {
        return "Hidden Field";
    }

    @Override
    public String getPropertyOptions() {
        return AppUtil.readPluginResource(getClass().getName(), "/properties/form/hiddenField.json", null, true, "message/form/HiddenField");
    }

    @Override
    public String getFormBuilderCategory() {
        return FormBuilderPalette.CATEGORY_GENERAL;
    }

    @Override
    public int getFormBuilderPosition() {
        return 100;
    }

    @Override
    public String getFormBuilderIcon() {
        return "<i class=\"fas fa-eye-slash\"></i>";
    }
    
    //Force to be readonly when it set to `Always Use Default Value`
    @Override
    public Boolean isReadonly(FormData formData) {
        if ("valueOnly".equalsIgnoreCase(getPropertyString("useDefaultWhenEmpty"))) {
            return true;
        } else {
            return super.isReadonly(formData);
        }
    }
    
    /**
     * to force the value stored for `Always Use Default Value` is always the default value
     */
    @Override
    public FormRowSet formatData(FormData formData) {
        FormRowSet rowSet = null;

        // get value
        String id = getPropertyString(FormUtil.PROPERTY_ID);
        if (id != null) {
            String value = FormUtil.getElementPropertyValue(this, formData);
            if ("valueOnly".equalsIgnoreCase(getPropertyString("useDefaultWhenEmpty"))) {
                value = getPropertyString("value");
            }
            if (value != null) {
                // set value into Properties and FormRowSet object
                FormRow result = new FormRow();
                result.setProperty(id, value);
                rowSet = new FormRowSet();
                rowSet.add(result);
            }
        }

        return rowSet;
    }
}

wflow-core/src/main/java/org/joget/apps/form/model/Form.java
package org.joget.apps.form.model;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import javax.servlet.http.HttpServletRequest;
import org.joget.apps.app.model.AppDefinition;
import org.joget.apps.app.service.AppPluginUtil;
import org.joget.apps.app.service.AppUtil;
import org.joget.apps.form.service.FormService;
import org.joget.apps.form.service.FormUtil;
import org.joget.apps.userview.model.Permission;
import org.joget.commons.util.SecurityUtil;
import org.joget.workflow.util.WorkflowUtil;
import org.json.JSONObject;

public class Form extends Element implements FormBuilderEditable, FormContainer {

    private Map<String, String[]> formMetas = new HashMap<String, String[]>();
    private Collection<FormAction> actions = new ArrayList<FormAction>();

    @Override
    public String getName() {
        return "Form";
    }

    @Override
    public String getVersion() {
        return "5.0.0";
    }

    @Override
    public String getDescription() {
        return "Form Element";
    }

    @Override
    public String renderTemplate(FormData formData, Map dataModel) {
        String template = "form.ftl";
        
        //for preview
        if (formData.getFormResult(FormService.PREVIEW_MODE) != null) {
            setFormMeta("json", new String[]{formData.getRequestParameter("json")});
        }

        // get current app
        AppDefinition appDef = AppUtil.getCurrentAppDefinition();
        if (appDef != null) {
            dataModel.put("appId", appDef.getAppId());
            dataModel.put("appVersion", appDef.getVersion());
        }
        
        // check whether in form builder
        boolean formBuilderActive = FormUtil.isFormBuilderActive();
       
        // check for quick edit mode
        boolean isQuickEditEnabled = (!"true".equals(getPropertyString("removeQuickEdit")) && !formBuilderActive && AppUtil.isQuickEditEnabled()) || (formBuilderActive && getParent() != null);
        dataModel.put("quickEditEnabled", isQuickEditEnabled);
        if (((Boolean) dataModel.get("includeMetaData") == true) || isAuthorize(formData)) {
            dataModel.put("isAuthorize", true);
            dataModel.put("isRecordExist", true);
            
            String paramName = FormUtil.getElementParameterName(this);
            setFormMeta(paramName+"_SUBMITTED", new String[]{"true"});
            String primaryKey = this.getPrimaryKeyValue(formData);

            if (getParent() == null) {
                boolean isRuntimeLoad = (formData.getFormResult(FormService.PREVIEW_MODE) == null || !dataModel.containsKey("elementMetaData"))
                        && !FormUtil.isFormSubmitted(this, formData);
                boolean urlHasId = (formData.getRequestParameter("id") != null || formData.getRequestParameter("fk_id") != null
                            || formData.getRequestParameter("fke_id") != null || formData.getRequestParameter("recordId") != null);
                
                if (isRuntimeLoad && urlHasId) {
                    //check for record exist
                    FormRowSet data = formData.getLoadBinderData(this);
                    if (data == null || data.isEmpty()) {
                        dataModel.put("isRecordExist", false);
                    }
                }
                
                if (formData.getRequestParameter(FormUtil.FORM_META_ORIGINAL_ID) != null &&
                        !formData.getRequestParameter(FormUtil.FORM_META_ORIGINAL_ID).isEmpty()) {
                    setFormMeta(FormUtil.FORM_META_ORIGINAL_ID, new String[]{formData.getRequestParameter(FormUtil.FORM_META_ORIGINAL_ID)});
                } else if (primaryKey != null) {
                    setFormMeta(FormUtil.FORM_META_ORIGINAL_ID, new String[]{primaryKey});
                } else {
                    setFormMeta(FormUtil.FORM_META_ORIGINAL_ID, new String[]{""});
                }
                
                //store form erros
                Map<String, String> errors = formData.getFormErrors();
                if (errors != null && !errors.isEmpty()) {
                    try {
                        JSONObject errorJson = new JSONObject();
                        errorJson.put("errors", errors);
                        setFormMeta(FormUtil.FORM_ERRORS_PARAM, new String[]{errorJson.toString()});
                    } catch (Exception e) {}
                }
            } else {
                String uniqueId = getCustomParameterName();
                if (formData.getRequestParameter(uniqueId + FormUtil.FORM_META_ORIGINAL_ID) != null &&
                        !formData.getRequestParameter(uniqueId + FormUtil.FORM_META_ORIGINAL_ID).isEmpty()) {
                    setFormMeta(uniqueId + FormUtil.FORM_META_ORIGINAL_ID, new String[]{formData.getRequestParameter(uniqueId + FormUtil.FORM_META_ORIGINAL_ID)});
                } else if (primaryKey != null) {
                    setFormMeta(uniqueId + FormUtil.FORM_META_ORIGINAL_ID, new String[]{primaryKey});
                } else {
                    setFormMeta(uniqueId + FormUtil.FORM_META_ORIGINAL_ID, new String[]{""});
                }
            }
            
            //to remove unuse nonces after submission
            if (getParent() == null) {
                HttpServletRequest request = WorkflowUtil.getHttpServletRequest();
                if (request != null) {
                    setFormMeta("_NONCE_TOKEN_REQUEST_HASH", new String[]{Integer.toString(request.hashCode())});
                }
            }

            dataModel.put("formMeta", formMetas);
        } else {
            dataModel.put("isAuthorize", false);
        }

        String html = FormUtil.generateElementHtml(this, formData, template, dataModel);
        return html;
    }

    @Override
    public String getClassName() {
        return getClass().getName();
    }

    @Override
    public String getLabel() {
        return getName();
    }

    @Override
    public String getPropertyOptions() {
        return AppUtil.readPluginResource(getClass().getName(), "/properties/form/form.json", null, true, "message/form/Form");
    }

    @Override
    public String getFormBuilderTemplate() {
        return "";
    }

    public void setFormMeta(String name, String[] values) {
        formMetas.put(name, values);
    }

    public String[] getFormMeta(String name) {
        return formMetas.get(name);
    }

    public Map getFormMetas() {
        return formMetas;
    }
    
    @Override
    public FormRowSet formatData(FormData formData) {
        if (FormUtil.isFormSubmitted(this, formData) && formData.getRequestParameter("_NONCE_TOKEN_REQUEST_HASH") != null) {
            try {
                int requestHash = Integer.parseInt(formData.getRequestParameter("_NONCE_TOKEN_REQUEST_HASH"));
                SecurityUtil.clearNonces(requestHash);
            } catch (Exception e) {}
        }
        return null;
    }

    public Collection<FormAction> getActions() {
        return actions;
    }

    public void setActions(Collection<FormAction> actions) {
        this.actions = actions;
    }
    
    public void addAction(FormAction action) {
        if (this.actions == null) {
            this.actions = new ArrayList<FormAction>();
        }
        this.actions.add(action);
    }
    
    public String getTooltips() {
        String tips = "{}";
        Map<String, String> messages = AppUtil.getAppMessageFromStore();
        try {
            JSONObject obj = new JSONObject();
            for (String key : messages.keySet()) {
                if (key.startsWith("tooltip." + getPropertyString(FormUtil.PROPERTY_ID) + ".")) {
                    obj.put(key, messages.get(key));
                }
            }
            
            tips = obj.toString();
        } catch (Exception e) {}
        
        return tips;
    }
    
    @Override
    public Boolean isAuthorize(FormData formData) {
        if (formData.getFormResult(FormService.PREVIEW_MODE) != null) {
            return true;
        }
        
        Boolean isAuthorize = isAuthorizeSet.get(formData);
        if (isAuthorize == null) {
            if (Permission.DEFAULT.equals(getPermissionKey(formData))) {
                Map permissionMap = (Map) getProperty("permission");
                if (permissionMap != null) {
                    isAuthorize = FormUtil.getPermissionResult(permissionMap, formData);
                } else {
                    isAuthorize = true;
                }
            } else {
                isAuthorize = true;
            }
            isAuthorizeSet.put(formData, isAuthorize);
        }
        
        return isAuthorize;
    }
    
    @Override
    public String getPermissionKey(FormData formData) {
        if (!permissionKeys.containsKey(formData)) {
            permissionKeys.put(formData, Permission.DEFAULT);
            Object[] rules = (Object[]) getProperty("permission_rules");
            if (rules != null && rules.length > 0) {
                for (Object rule : rules) {
                    Map ruleMap = (Map) rule;
                    String key = ruleMap.get("permission_key").toString();
                    boolean isAuthorize = FormUtil.getPermissionResult((Map) ruleMap.get("permission"), formData);
                    if (isAuthorize) {
                        permissionKeys.put(formData, key);
                        break;
                    }
                }
            }
        }
        return permissionKeys.get(formData);
    }
    
    @Override
    public Map<String, String> getElementStyles(String styleClass, Map<String, String> attrs) {
        Map<String, String> styles = super.getElementStyles(styleClass, attrs);
        
        //section default styles
        if (getParent() == null) {
            String[] keys = new String[]{"section-", "section-header-", "section-fieldLabel-", "section-fieldInput-"};
            String[] cssClass = new String[] {

wflow-core/src/main/resources/templates/customHTML.ftl
<div class="form-cell customHtml <#if element.properties.label == "">no_label</#if> ${element.properties.id!}" ${elementMetaData!}>
    <#if element.properties.label != "">
        <label class="label">${element.properties.label!} <span class="form-cell-validator">${decoration}</span><#if error??> <span class="form-error-message">${error}</span></#if></label>
    </#if>
    <div class="form-cell-value <#if element.properties.label == ''>form-cell-full</#if>">
    ${value!}
    </div>
    <div style="clear:both;"></div>
</div>

wflow-core/src/main/resources/templates/datePicker.ftl
<div class="form-cell" ${elementMetaData!}>
<#if element.properties.readonly! != 'true'>
    <#if !(request.getAttribute("org.joget.apps.form.lib.DatePicker_EDITABLE")??)>
        <#if locale! != ''>
            <script type="text/javascript" src="${request.contextPath}/js/jquery/ui/i18n/jquery.ui.datepicker-${locale}.js"></script>
        </#if>
        <script type="text/javascript" src="${request.contextPath}/plugin/org.joget.apps.form.lib.DatePicker/js/jquery.placeholder.min.js"></script>
        <link rel="stylesheet" href="${request.contextPath}/plugin/org.joget.apps.form.lib.DatePicker/css/jquery-ui-timepicker-addon.css" />
        <script type="text/javascript" src="${request.contextPath}/plugin/org.joget.apps.form.lib.DatePicker/js/jquery-ui-timepicker-addon.js"></script>
        <#if isBE!>
            <script type="text/javascript" src="${request.contextPath}/js/jquery/ui/i18n/jquery.ui.datepicker.ext.be.js"></script>
        </#if>
    </#if>
<script type="text/javascript">
    $(document).ready(function() {
        $("#${elementParamName!}_${element.properties.elementUniqueKey!}").cdatepicker({
                        showOn: "button",
                        buttonImage: "${request.contextPath}/css/images/calendar.png",
                        buttonImageOnly: true,
                        changeMonth: true,
                        changeYear: true,
                        timeInput: true,
                        buttonText : ''
                        <#if element.properties.format24hr! == ''>
                        ,timeFormat: "hh:mm tt"
                        </#if>
                        <#if element.properties.format! != ''>
                        ,dateFormat: "${element.properties.format}"
                        </#if>
                        <#if element.properties.yearRange! != ''>
                        ,yearRange: "${element.properties.yearRange}"
                        </#if>
                        <#if element.properties.startDateFieldId! != ''>
                        ,startDateFieldId: "${element.properties.startDateFieldId}"
                        </#if>
                        <#if element.properties.endDateFieldId! != ''>
                        ,endDateFieldId: "${element.properties.endDateFieldId}"
                        </#if>
                        <#if element.properties.currentDateAs! != ''>
                        ,currentDateAs: "${element.properties.currentDateAs}"
                        </#if>
                        <#if element.properties.datePickerType! != ''>
                        ,datePickerType: "${element.properties.datePickerType}"
                        </#if>
                        <#if element.properties.firstday! != ''>
                        ,firstDay: "${element.properties.firstday}"
                        </#if>
                        <#if isBE! && element.properties.datePickerType! != 'timeOnly'>
                        ,isBE: true
                        ,autoConversionField: false
                        </#if>
                        <#if isRTL!>
                            ,isRTL: true
                        </#if>
                        <#if (element.properties.disableWeekends! == 'true')>
                        ,beforeShowDay: $.datepicker.noWeekends
                        </#if>
                        ,timeOnlyTitle : "@@form.datepicker.chooseTime@@"
                        ,timeText : "@@form.datepicker.time@@"
                        ,hourText : "@@form.datepicker.hour@@"
                        ,minuteText : "@@form.datepicker.minute@@"
                        ,currentText : "@@form.datepicker.now@@"
                        ,closeText : "@@form.datepicker.done@@"
        });

        $(window).on("resize orientationchange", function(){
            $("#${elementParamName!}_${element.properties.elementUniqueKey!}").datepicker("hide");
        });
    });
</script>
</#if>
    <label field-tooltip="${elementParamName!}" class="label" for="${elementParamName!}_${element.properties.elementUniqueKey!}">${element.properties.label} <span class="form-cell-validator">${decoration}</span><#if element.properties.showUserTimeZone! == 'true' && !(element.properties.readonly! == 'true' && element.properties.readonlyLabel! == 'true') ><br/><span>(${userTimeZone!?html})</span></#if><#if error??> <span class="form-error-message">${error}</span></#if></label>
    <#if (element.properties.readonly! == 'true' && element.properties.readonlyLabel! == 'true') >
        <span>${value!?html} <#if element.properties.showUserTimeZone! == 'true' >(${userTimeZone!?html})</#if></span>
        <input id="${elementParamName!}" name="${elementParamName!}" type="hidden" value="${value!?html}" />
    <#else>
        <input id="${elementParamName!}_${element.properties.elementUniqueKey!}" name="${elementParamName!}" type="text" <#if element.properties.size?has_content>size="${element.properties.size!}"</#if> value="${value!?html}" class="${elementParamName!}<#if (element.properties.allowManual! != 'true' && element.properties.readonly! != 'true')> no-manual-input</#if> <#if error??>form-error-cell</#if>" <#if (element.properties.allowManual! != 'true' || element.properties.readonly! == 'true')>readonly</#if> placeholder="<#if (element.properties.placeholder! != '')>${element.properties.placeholder!?html}<#else>${displayFormat!?html}</#if>" />
    </#if>
</div>

wflow-core/src/main/resources/templates/form.ftl
<#if isAuthorize>
    <#if quickEditEnabled && appId??>
    <div class="quickEdit">
         <a href="${request.contextPath}/web/console/app/${appId}/${appVersion}/form/builder/${element.properties.id!}" target="_blank"><i class="fas fa-pencil-alt"></i> @@adminBar.label.form@@: ${element.properties.name!?html}</a>
    </div>
    </#if>
    
    <#if isRecordExist >
        <#if !element.parent??>
        <form id="${element.properties.id!}" name="${element.properties.id!}" class="form-container <#if element.properties.readonly! == 'true'>readonly</#if>" ${elementMetaData!} <#if element.properties.url??>action="${element.properties.url}"</#if> method="POST" enctype="multipart/form-data">
        </#if>
            <#assign keys = element.formMetas?keys>
            <#list keys as key>
                <#assign metaValues = element.formMetas[key]>
                <#list metaValues as v>
                    <input type="hidden" value="${v!?html}" name="${key}" />
                </#list>
            </#list>
            <#if error??><div class="form-error-message">${error}</div></#if>
            <#list element.children as e>
                ${e.render(formData, includeMetaData!false)}
            </#list>
            <script>
                $(function(){
                    FormUtil.populateTooltip(${element.tooltips!});
                });
            </script>
        <#if !element.parent??>
        </form>
        <script>
            //put it outside the jquery ready function is because the csrf token will be populate correctly when jquery ready.
            $("form#${element.properties.id!}").on("submit", function(){
                //make sure csrf token is set correctly
                var form = this;
                if ($(form).find("[name='"+ ConnectionManager.tokenName +"']").length === 0) {
                    $(form).append('<input type="hidden" name="'+ConnectionManager.tokenName+'" value="'+ConnectionManager.tokenValue+'"/>');
                }
                return true;
            });

            $(function(){
                UrlUtil.solveUrlParamFormFieldConflict($("form#${element.properties.id!}"));

                $("#section-actions button, #section-actions input").click(function(){
                    $.blockUI({ css: { 
                        border: 'none', 
                        padding: '15px', 
                        backgroundColor: '#000', 
                        '-webkit-border-radius': '10px', 
                        '-moz-border-radius': '10px', 
                        opacity: .3, 
                        color: '#fff' 
                    }, message : "<h1>@@form.form.message.wait@@</h1>" }); 
                    return true;
                });
                if (!UI.isMobileUserAgent()) {
                    setTimeout(function(){
                        $('form[name]:not(.readonly)').first().find("input:visible, select:visible, textarea:visible, label[tabindex]:visible, .focusable").first().focus().trigger("focusable");
                    }, 10);    
                }
                $('form').off('keyup', "label[tabindex]");
                $('form').on('keyup', "label[tabindex]", function(e) {
                    var keyCode = e.keyCode || e.which;
                    if (keyCode === 13) { 
                        e.preventDefault();
                        $(this).find("input").trigger("click");
                        return false;
                    }
                });
            });
        </script>
        </#if>
    <#else>
        <h3>@@form.form.message.recordNotFound@@</h3>
    </#if>    
<#else>
    <#if element.properties.noPermissionMessage?? && element.properties.noPermissionMessage! != "">
        <h3>${element.properties.noPermissionMessage!}</h3>
    <#else>
        <h3>@@form.form.message.noPermission@@</h3>
    </#if>
</#if>

wflow-core/src/main/resources/templates/idGeneratorField.ftl
<#if includeMetaData>
    <div class="form-cell" ${elementMetaData!}>
        <#if element.properties.hidden! != 'true'>
            <label class="label">${element.properties.label}</label>
            <span>@@form.idgeneratorfield.auto@@</span>
        </#if>
    </div>
<#else>
    <#if element.properties.hidden! == 'true'>
        <#if value?? ><input id="${elementParamName!}" name="${elementParamName!}" type="hidden" value="${value!?html}" /></#if>
    <#else>
        <div class="form-cell" ${elementMetaData!}>
            <label field-tooltip="${elementParamName!}" class="label">${element.properties.label}</label>
            <span>${value!?html}<#if !value?? || value == ''>@@form.idgeneratorfield.auto@@</#if></span>
            <#if value?? ><input id="${elementParamName!}" name="${elementParamName!}" type="hidden" value="${value!?html}" /></#if>
        </div>
    </#if>
</#if>

wflow-core/src/main/resources/templates/progressiveTheme_horizontalMenu.ftl
<div id="${sidebar_id!}" class="${sidebar_classes!}">
    ${sidebar_inner_before!}
    ${menus!}
    ${sidebar_inner_after!}
</div>

wflow-core/src/main/resources/templates/radio.ftl
<div class="form-cell" ${elementMetaData!}>
    <label  field-tooltip="${elementParamName!}" class="label">${element.properties.label} <span class="form-cell-validator">${decoration}</span><#if error??> <span class="form-error-message">${error}</span></#if></label>
    <#if (element.properties.fullWidth?? && element.properties.fullWidth! != "" && element.properties.fullWidth! == 'true') >
        <div class="form-cell-value fullWidth" id="${elementParamName!}${element.properties.elementUniqueKey!}">
    <#else>
        <div class="form-cell-value" id="${elementParamName!}${element.properties.elementUniqueKey!}">
    </#if>
    <#list options as option>
        <#if (element.properties.readonly! == 'true' && element.properties.readonlyLabel! == 'true') >
            <#if value?? && value == option.value!>
                <label class="readonly_label">
                    <span>${option.label!?html}</span>
                </label>
            </#if>
        <#else>
            <label tabindex="0" >
                <input grouping="${option.grouping!?html}" <#if element.properties.readonly! != 'true'>id="${elementParamName!}"</#if> name="${elementParamName!}" type="radio" value="${option.value!?html}" <#if error??>class="form-error-cell"</#if> <#if element.properties.readonly! == 'true'> disabled</#if> <#if value?? && value == option.value!>checked</#if> />
                <i></i>    
                ${option.label!?html}
            </label>
        </#if>
    </#list>
        <#if element.properties.readonly! == 'true'><input id="${elementParamName!}" name="${elementParamName!}" type="hidden" value="${value!}" /></#if>
    </div>
    <div style="clear:both;"></div>

    <#if (element.properties.controlField?? && element.properties.controlField! != "" && !(element.properties.readonly! == 'true' && element.properties.readonlyLabel! == 'true')) >
        <script type="text/javascript">
            $(document).ready(function(){
                $("#${elementParamName!}${element.properties.elementUniqueKey!}").dynamicOptions({
                    controlField : "${element.properties.controlFieldParamName!}",
                    paramName : "${elementParamName!}",
                    type : "radio",
                    readonly : "${element.properties.readonly!}",
                    nonce : "${element.properties.nonce!}",
                    binderData : "${element.properties.binderData!}",
                    appId : "${element.properties.appId!}",
                    appVersion : "${element.properties.appVersion!}",
                    contextPath : "${request.contextPath}"
                });
            });
        </script>
    </#if>
</div>

wflow-core/src/main/resources/templates/universalTheme_horizontalMenu.ftl
<div id="${sidebar_id!}" class="${sidebar_classes!}">
    ${sidebar_inner_before!}
    ${menus!}
    ${sidebar_inner_after!}
</div>